on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 25 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
